### ISSUE TITLE
eredis and pooler - pair not made in heaven

### ISSUE THREAD

**Issue by sdebnath** [seth/pooler#60]
This has occurred too many times for me and I am not sure what could be the cause. Hoping someone else has experienced the issue and can provide some workarounds. 

I manage 5 riak connections and 1 redis via pooler on my application. After N weeks all of a sudden eredis connections start reporting the below while riak connections are fine:

    2016-04-04 19:17:53 =SUPERVISOR REPORT====
         Supervisor: {local,pooler_redis01_member_sup}
         Context:    child_terminated
         Reason:     killed
         Offender:   [{pid,<0.4356.64>},{name,eredis},{mfargs,{eredis,start_link,undefined}},{restart_type,temporary},{shutdown,brutal_kill},{child_type,worker}]

The kills continues after the first error and doesn't really seem to be able to recover.

My config is as follows:

    [
      {pooler, [
        {pools, [
          [{name, riak01},
           {group, riak},
           {max_count, 5000},
           {init_count, 10},
           {start_mfa, {riakc_pb_socket, start_link, ["riak-01.prod.domain.com", 8087]}}],
    
          [{name, riak02},
           {group, riak},
           {max_count, 5000},
           {init_count, 10},
           {start_mfa, {riakc_pb_socket, start_link, ["riak-02.prod.domain.com", 8087]}}],
    
          [{name, riak03},
           {group, riak},
           {max_count, 5000},
           {init_count, 10},
           {start_mfa, {riakc_pb_socket, start_link, ["riak-03.prod.domain.com", 8087]}}],
    
          [{name, riak04},
           {group, riak},
           {max_count, 5000},
           {init_count, 10},
           {start_mfa, {riakc_pb_socket, start_link, ["riak-04.prod.domain.com", 8087]}}],
    
          [{name, riak05},
           {group, riak},
           {max_count, 5000},
           {init_count, 10},
           {start_mfa, {riakc_pb_socket, start_link, ["riak-05.prod.domain.com", 8087]}}],
    
          [{name, redis01},
           {group, redis},
           {max_count, 5000},
           {init_count, 10},
           {start_mfa, {eredis, start_link, ["redis.prod.domain.com", 6379]}}]
         ]}
      ]},

Riak and redis are both operating and being used successfully by other services. Open file descriptors for the beam.smp process is about 106 and limited to 65536. Unfortunately not much else in the log. Any help appreciated.

**Comment by sata** [comment]
@sdebnath: could this be due to culling of stale members? i.e number of processes grows from init_count to a higher number and are culled after 1 minute[1]. The way pooler kills workers matches the brutal_kill response, at least the default[2] and [3]. You can use the custom stop MFA added in #45.

The 'correct' way of terminating a simple_one_for_one child is though by going through the supervisor:
`supervisor:terminate_child(Sup, Id)` rather than using exit/2. Though with the custom stop mfa you can't make this call since you only got a pid, which requires you to handle it in the client code. Shouldn't be too difficult to figure out which member_sup it is by the record when calling terminate_pid. I'll have a look in the weekend.

@seth: the use of exit/2, is it due to avoid putting any tension on the member_sup supervisor? 

[1] https://github.com/seth/pooler/#culling-stale-members
[2] https://github.com/seth/pooler/blob/549aad444e07f0edd911b055f37af5640b4c4b6e/src/pooler.erl#L923
[3] https://github.com/seth/pooler/blob/549aad444e07f0edd911b055f37af5640b4c4b6e/src/pooler.hrl#L9

**Comment by sata** [comment]
Done, #66 should sort this out for you.

**Comment by seth** [comment]
With #66 merged, I'm going to close this. If still an issue, please re-open.
